# Generated by Django 3.1.1 on 2020-09-08 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalappRoles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('short_name', models.TextField(blank=True, null=True)),
                ('long_name', models.TextField(blank=True, null=True)),
                ('display_name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PortalappPersoninformation',
            fields=[
                ('email', models.CharField(max_length=100)),
                ('firstname', models.TextField(blank=True, null=True)),
                ('lastname', models.TextField(blank=True, null=True)),
                ('telephone1', models.CharField(blank=True, max_length=15, null=True)),
                ('telephone2', models.CharField(blank=True, max_length=15, null=True)),
                ('clg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('deptid', models.IntegerField()),
                ('roll_no', models.TextField(blank=True, null=True)),
                ('createdondate', models.DateField()),
                ('is_active', models.IntegerField()),
                ('roleid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='portal.portalapproles')),
            ],
        ),
    ]
