# Generated by Django 3.1.1 on 2020-09-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portalapppersoninformation',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='portalapproles',
            options={'managed': False},
        ),
    ]
