# Generated by Django 3.1.1 on 2020-09-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20200908_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortalappForlogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'portalapp_forlogin',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='portalapppersoninformation',
            table='portalapp_personinformation',
        ),
        migrations.AlterModelTable(
            name='portalapproles',
            table='portalapp_roles',
        ),
    ]
