# Generated by Django 3.1.1 on 2020-09-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_newproject_tech'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tech_used',
        ),
        migrations.AddField(
            model_name='project',
            name='tech_used',
            field=models.ManyToManyField(to='projects.Tech'),
        ),
    ]
